version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: cd delivery && gradle clean build
  tests:
    - run: gradle test
  deploy:
    - run: ls
workflows:
  version:2
  build-test-and-deploy:
    jobs:
        - build
        - tests:
          requires:
            - build
        - deploy
          requires:
            - tests